apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: staging-flask.app.com
      http:
        paths:
          - path: /
            backend:
              serviceName: flask-app-staging
              servicePort: 8080
